# Generated by Django 4.2.20 on 2025-05-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaWyszukiwan',
            fields=[
                ('ID_Historii', models.AutoField(primary_key=True, serialize=False)),
                ('Data_wyszukiwania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historia_wyszukiwan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('ID_Kategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Kategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Miejsce',
            fields=[
                ('ID_Miejsca', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=100)),
                ('Adres', models.CharField(max_length=100)),
                ('Opis', models.CharField(max_length=100)),
                ('Data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Miejsce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('ID_Recenzja', models.AutoField(primary_key=True, serialize=False)),
                ('Ocena', models.IntegerField()),
                ('Komentarz', models.CharField(max_length=100)),
                ('Data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Recenzja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('ID_Regionu', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('ID_Uprawnienia', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Uprawnienia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('ID_Użytkownik', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=100)),
                ('Nazwisko', models.CharField(max_length=100)),
                ('Mail', models.CharField(max_length=100)),
                ('Hasło', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Użytkownik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zdjęcia',
            fields=[
                ('ID_Zdjęcie', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Zdjęcia',
                'managed': False,
            },
        ),
    ]
