# Generated by Django 5.2.1 on 2025-05-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('ID_Ranking', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=100)),
                ('Opis', models.TextField(blank=True, null=True)),
                ('Data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankingi',
                'db_table': 'Ranking',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='miejsce',
            options={'managed': False, 'verbose_name': 'Miejsce', 'verbose_name_plural': 'Miejsca'},
        ),
    ]
