# Generated by Django 5.2 on 2025-05-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ranking_alter_miejsce_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'managed': True, 'verbose_name': 'Ranking', 'verbose_name_plural': 'Rankingi'},
        ),
    ]
